language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-29.0.3
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck


