sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-29.0.3
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
before_script:
  - echo no | create avd — name android28 — package “system-images;android-28;default;x86”
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedCheck


