# Use the Travis Container-Based Infrastructure
sudo: false
language: android

jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-29.0.3
    - android-28

before_install:
  - chmod +x gradlew
  # Install the rest of tools (e.g., avdmanager)
  - yes | sdkmanager tools
  # Install the system image
  - yes | sdkmanager "system-images;android-28;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-28;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck


